# Generated by Django 3.2.12 on 2022-08-16 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=70, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Producto')),
                ('nombreCategoria', models.CharField(max_length=70, verbose_name='Nombre de Producto')),
                ('valorProducto', models.IntegerField(verbose_name='Valor de Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.categoria')),
            ],
        ),
    ]
